// @generated by client/scripts/generate-help-manifest.mjs from client/src/assets/docs/*-manual.md — do not edit by hand.

/// `(manual_id, path relative to repository root)`
pub const HELP_MANUAL_FILES: &[(&str, &str)] = &[
    ("pos", "client/src/assets/docs/pos-manual.md"),
    ("reports", "client/src/assets/docs/reports-manual.md"),
    ("insights", "client/src/assets/docs/insights-manual.md"),
];
