// @generated by scripts/generate-staff-avatars.mjs — do not edit by hand
export const STAFF_AVATAR_KEYS = ["ros_default","lorelei_01","lorelei_02","lorelei_03","lorelei_04","lorelei_05","lorelei_06","lorelei_07","lorelei_08","lorelei_09","lorelei_10","lorelei_11","lorelei_12","lorelei_13","lorelei_14","lorelei_15","lorelei_16","lorelei_17","lorelei_18","lorelei_19","lorelei_20","lorelei_21","lorelei_22","lorelei_23","lorelei_24","lorelei_25","lorelei_26","lorelei_27","lorelei_28","avataaars_01","avataaars_02","avataaars_03","avataaars_04","avataaars_05","avataaars_06","avataaars_07","avataaars_08","avataaars_09","avataaars_10","avataaars_11","avataaars_12","avataaars_13","avataaars_14","avataaars_15","avataaars_16","avataaars_17","avataaars_18","avataaars_19","avataaars_20","avataaars_21","avataaars_22","adventurer_01","adventurer_02","adventurer_03","adventurer_04","adventurer_05","adventurer_06","adventurer_07","adventurer_08","adventurer_09","adventurer_10","adventurer_11","adventurer_12","adventurer_13","adventurer_14","adventurer_15","adventurer_16","adventurer_17","adventurer_18","adventurer_19","adventurer_20","adventurer_21","adventurer_22"] as const;

export type StaffAvatarKey = (typeof STAFF_AVATAR_KEYS)[number];

export type StaffAvatarGroup = "default" | "lorelei" | "avataaars" | "adventurer";

export interface StaffAvatarCatalogEntry {
  key: StaffAvatarKey;
  group: StaffAvatarGroup;
}

export const STAFF_AVATAR_CATALOG: StaffAvatarCatalogEntry[] = [
  {
    "key": "ros_default",
    "group": "default"
  },
  {
    "key": "lorelei_01",
    "group": "lorelei"
  },
  {
    "key": "lorelei_02",
    "group": "lorelei"
  },
  {
    "key": "lorelei_03",
    "group": "lorelei"
  },
  {
    "key": "lorelei_04",
    "group": "lorelei"
  },
  {
    "key": "lorelei_05",
    "group": "lorelei"
  },
  {
    "key": "lorelei_06",
    "group": "lorelei"
  },
  {
    "key": "lorelei_07",
    "group": "lorelei"
  },
  {
    "key": "lorelei_08",
    "group": "lorelei"
  },
  {
    "key": "lorelei_09",
    "group": "lorelei"
  },
  {
    "key": "lorelei_10",
    "group": "lorelei"
  },
  {
    "key": "lorelei_11",
    "group": "lorelei"
  },
  {
    "key": "lorelei_12",
    "group": "lorelei"
  },
  {
    "key": "lorelei_13",
    "group": "lorelei"
  },
  {
    "key": "lorelei_14",
    "group": "lorelei"
  },
  {
    "key": "lorelei_15",
    "group": "lorelei"
  },
  {
    "key": "lorelei_16",
    "group": "lorelei"
  },
  {
    "key": "lorelei_17",
    "group": "lorelei"
  },
  {
    "key": "lorelei_18",
    "group": "lorelei"
  },
  {
    "key": "lorelei_19",
    "group": "lorelei"
  },
  {
    "key": "lorelei_20",
    "group": "lorelei"
  },
  {
    "key": "lorelei_21",
    "group": "lorelei"
  },
  {
    "key": "lorelei_22",
    "group": "lorelei"
  },
  {
    "key": "lorelei_23",
    "group": "lorelei"
  },
  {
    "key": "lorelei_24",
    "group": "lorelei"
  },
  {
    "key": "lorelei_25",
    "group": "lorelei"
  },
  {
    "key": "lorelei_26",
    "group": "lorelei"
  },
  {
    "key": "lorelei_27",
    "group": "lorelei"
  },
  {
    "key": "lorelei_28",
    "group": "lorelei"
  },
  {
    "key": "avataaars_01",
    "group": "avataaars"
  },
  {
    "key": "avataaars_02",
    "group": "avataaars"
  },
  {
    "key": "avataaars_03",
    "group": "avataaars"
  },
  {
    "key": "avataaars_04",
    "group": "avataaars"
  },
  {
    "key": "avataaars_05",
    "group": "avataaars"
  },
  {
    "key": "avataaars_06",
    "group": "avataaars"
  },
  {
    "key": "avataaars_07",
    "group": "avataaars"
  },
  {
    "key": "avataaars_08",
    "group": "avataaars"
  },
  {
    "key": "avataaars_09",
    "group": "avataaars"
  },
  {
    "key": "avataaars_10",
    "group": "avataaars"
  },
  {
    "key": "avataaars_11",
    "group": "avataaars"
  },
  {
    "key": "avataaars_12",
    "group": "avataaars"
  },
  {
    "key": "avataaars_13",
    "group": "avataaars"
  },
  {
    "key": "avataaars_14",
    "group": "avataaars"
  },
  {
    "key": "avataaars_15",
    "group": "avataaars"
  },
  {
    "key": "avataaars_16",
    "group": "avataaars"
  },
  {
    "key": "avataaars_17",
    "group": "avataaars"
  },
  {
    "key": "avataaars_18",
    "group": "avataaars"
  },
  {
    "key": "avataaars_19",
    "group": "avataaars"
  },
  {
    "key": "avataaars_20",
    "group": "avataaars"
  },
  {
    "key": "avataaars_21",
    "group": "avataaars"
  },
  {
    "key": "avataaars_22",
    "group": "avataaars"
  },
  {
    "key": "adventurer_01",
    "group": "adventurer"
  },
  {
    "key": "adventurer_02",
    "group": "adventurer"
  },
  {
    "key": "adventurer_03",
    "group": "adventurer"
  },
  {
    "key": "adventurer_04",
    "group": "adventurer"
  },
  {
    "key": "adventurer_05",
    "group": "adventurer"
  },
  {
    "key": "adventurer_06",
    "group": "adventurer"
  },
  {
    "key": "adventurer_07",
    "group": "adventurer"
  },
  {
    "key": "adventurer_08",
    "group": "adventurer"
  },
  {
    "key": "adventurer_09",
    "group": "adventurer"
  },
  {
    "key": "adventurer_10",
    "group": "adventurer"
  },
  {
    "key": "adventurer_11",
    "group": "adventurer"
  },
  {
    "key": "adventurer_12",
    "group": "adventurer"
  },
  {
    "key": "adventurer_13",
    "group": "adventurer"
  },
  {
    "key": "adventurer_14",
    "group": "adventurer"
  },
  {
    "key": "adventurer_15",
    "group": "adventurer"
  },
  {
    "key": "adventurer_16",
    "group": "adventurer"
  },
  {
    "key": "adventurer_17",
    "group": "adventurer"
  },
  {
    "key": "adventurer_18",
    "group": "adventurer"
  },
  {
    "key": "adventurer_19",
    "group": "adventurer"
  },
  {
    "key": "adventurer_20",
    "group": "adventurer"
  },
  {
    "key": "adventurer_21",
    "group": "adventurer"
  },
  {
    "key": "adventurer_22",
    "group": "adventurer"
  }
];
