// @generated by client/scripts/generate-help-manifest.mjs from client/src/assets/docs/*-manual.md — do not edit by hand.
import type { HelpManual } from "./help-manifest.types";

import manual_0_raw from "../../assets/docs/pos-manual.md?raw";
import manual_1_raw from "../../assets/docs/reports-manual.md?raw";
import manual_2_raw from "../../assets/docs/insights-manual.md?raw";

export const HELP_MANUALS: HelpManual[] = [
  {
    id: "pos",
    title: "Register (POS)",
    summary: "Opening the till, dashboard, ringing sales, suit swap, checkout, wedding lookup.",
    markdown: manual_0_raw,
    tags: ["pos","register","checkout"],
  },
  {
    id: "reports",
    title: "Reports (curated)",
    summary: "Back Office Reports library: fixed tiles, booked vs completed basis, CSV, Admin-only margin; vs Insights (Metabase).",
    markdown: manual_1_raw,
    tags: ["reports","analytics","insights","pivot","margin","rbac"],
  },
  {
    id: "insights",
    title: "Insights (Metabase)",
    summary: "Metabase analytics in-app, Metabase login, Staff commission payouts, permissions. For the curated Reports library, open the Reports (curated) manual in Help.",
    markdown: manual_2_raw,
    tags: ["insights","metabase","reports","analytics","commission","payouts"],
  },
];

export function helpManualById(id: string): HelpManual | undefined {
  return HELP_MANUALS.find((m) => m.id === id);
}
