-- Restore ROS operational custom-order SKUs after Counterpoint catalog imports.
--
-- Counterpoint item numbers 100/105/110/200 can overlap the seeded ROS custom
-- order products. Those ROS SKUs are used by the Register custom order buttons
-- and must never be owned by imported Counterpoint catalog rows.

INSERT INTO products (
    id,
    category_id,
    catalog_handle,
    name,
    brand,
    description,
    base_retail_price,
    base_cost,
    spiff_amount,
    variation_axes,
    images,
    is_active,
    primary_vendor_id,
    excludes_from_loyalty,
    is_bundle,
    track_low_stock,
    pos_line_kind,
    data_source,
    tax_category,
    employee_markup_percent,
    employee_extra_amount,
    nuorder_last_image_sync_at,
    tax_category_override
)
VALUES
    (
        'b7c0a011-0011-4011-8011-000000000011',
        'b7c0a010-0010-4010-8010-000000000010',
        'ros-custom-hsm-suit',
        'HSM SUIT (Custom)',
        'Hart Schaffner Marx',
        'Hart Schaffner & Marx made-to-measure suit. Price set at booking via Register custom order form.',
        0.00,
        0.00,
        0.00,
        '{}',
        '{}',
        true,
        NULL,
        false,
        false,
        false,
        NULL,
        NULL,
        'clothing',
        NULL,
        0.00,
        NULL,
        NULL
    ),
    (
        'b7c0a012-0012-4012-8012-000000000012',
        'b7c0a010-0010-4010-8010-000000000010',
        'ros-custom-hsm-sport-coat',
        'HSM SPORT COAT (Custom)',
        'Hart Schaffner Marx',
        'Hart Schaffner & Marx made-to-measure sport coat. Price set at booking via Register custom order form.',
        0.00,
        0.00,
        0.00,
        '{}',
        '{}',
        true,
        NULL,
        false,
        false,
        false,
        NULL,
        NULL,
        'clothing',
        NULL,
        0.00,
        NULL,
        NULL
    ),
    (
        'b7c0a013-0013-4013-8013-000000000013',
        'b7c0a010-0010-4010-8010-000000000010',
        'ros-custom-hsm-slacks',
        'HSM SLACKS (Custom)',
        'Hart Schaffner Marx',
        'Hart Schaffner & Marx made-to-measure slacks. Price set at booking via Register custom order form.',
        0.00,
        0.00,
        0.00,
        '{}',
        '{}',
        true,
        NULL,
        false,
        false,
        false,
        NULL,
        NULL,
        'clothing',
        NULL,
        0.00,
        NULL,
        NULL
    ),
    (
        'b7c0a014-0014-4014-8014-000000000014',
        'b7c0a010-0010-4010-8010-000000000010',
        'ros-custom-individualized-shirt',
        'INDIVIDUALIZED SHIRT (Custom)',
        'Individualized Shirts',
        'Individualized Shirts made-to-measure dress shirt. Price set at booking via Register custom order form.',
        0.00,
        0.00,
        0.00,
        '{}',
        '{}',
        true,
        NULL,
        false,
        false,
        false,
        NULL,
        NULL,
        'clothing',
        NULL,
        0.00,
        NULL,
        NULL
    )
ON CONFLICT (id) DO UPDATE SET
    category_id = EXCLUDED.category_id,
    catalog_handle = EXCLUDED.catalog_handle,
    name = EXCLUDED.name,
    brand = EXCLUDED.brand,
    description = EXCLUDED.description,
    base_retail_price = EXCLUDED.base_retail_price,
    base_cost = EXCLUDED.base_cost,
    spiff_amount = EXCLUDED.spiff_amount,
    variation_axes = EXCLUDED.variation_axes,
    is_active = EXCLUDED.is_active,
    excludes_from_loyalty = EXCLUDED.excludes_from_loyalty,
    is_bundle = EXCLUDED.is_bundle,
    track_low_stock = EXCLUDED.track_low_stock,
    pos_line_kind = EXCLUDED.pos_line_kind,
    data_source = EXCLUDED.data_source,
    tax_category = EXCLUDED.tax_category,
    employee_markup_percent = EXCLUDED.employee_markup_percent,
    employee_extra_amount = EXCLUDED.employee_extra_amount,
    tax_category_override = EXCLUDED.tax_category_override;

UPDATE product_variants
SET counterpoint_item_key = NULL
WHERE id IN (
    'b7c0a015-0015-4015-8015-000000000015',
    'b7c0a016-0016-4016-8016-000000000016',
    'b7c0a017-0017-4017-8017-000000000017',
    'b7c0a018-0018-4018-8018-000000000018'
);

INSERT INTO product_variants (
    id,
    product_id,
    sku,
    variation_values,
    variation_label,
    stock_on_hand,
    reorder_point,
    images,
    retail_price_override,
    cost_override,
    shelf_labeled_at,
    barcode,
    reserved_stock,
    vendor_upc,
    counterpoint_item_key,
    track_low_stock,
    web_published,
    web_price_override,
    web_gallery_order,
    counterpoint_prc_2,
    counterpoint_prc_3,
    nuorder_id,
    on_layaway,
    default_location_id
)
VALUES
    (
        'b7c0a015-0015-4015-8015-000000000015',
        'b7c0a011-0011-4011-8011-000000000011',
        '100',
        '{}',
        NULL,
        0,
        0,
        '{}',
        NULL,
        NULL,
        NULL,
        NULL,
        0,
        NULL,
        NULL,
        false,
        false,
        NULL,
        0,
        NULL,
        NULL,
        NULL,
        0,
        NULL
    ),
    (
        'b7c0a016-0016-4016-8016-000000000016',
        'b7c0a012-0012-4012-8012-000000000012',
        '105',
        '{}',
        NULL,
        0,
        0,
        '{}',
        NULL,
        NULL,
        NULL,
        NULL,
        0,
        NULL,
        NULL,
        false,
        false,
        NULL,
        0,
        NULL,
        NULL,
        NULL,
        0,
        NULL
    ),
    (
        'b7c0a017-0017-4017-8017-000000000017',
        'b7c0a013-0013-4013-8013-000000000013',
        '110',
        '{}',
        NULL,
        0,
        0,
        '{}',
        NULL,
        NULL,
        NULL,
        NULL,
        0,
        NULL,
        NULL,
        false,
        false,
        NULL,
        0,
        NULL,
        NULL,
        NULL,
        0,
        NULL
    ),
    (
        'b7c0a018-0018-4018-8018-000000000018',
        'b7c0a014-0014-4014-8014-000000000014',
        '200',
        '{}',
        NULL,
        0,
        0,
        '{}',
        NULL,
        NULL,
        NULL,
        NULL,
        0,
        NULL,
        NULL,
        false,
        false,
        NULL,
        0,
        NULL,
        NULL,
        NULL,
        0,
        NULL
    )
ON CONFLICT (id) DO UPDATE SET
    product_id = EXCLUDED.product_id,
    sku = EXCLUDED.sku,
    variation_values = EXCLUDED.variation_values,
    variation_label = EXCLUDED.variation_label,
    stock_on_hand = EXCLUDED.stock_on_hand,
    reorder_point = EXCLUDED.reorder_point,
    images = EXCLUDED.images,
    retail_price_override = EXCLUDED.retail_price_override,
    cost_override = EXCLUDED.cost_override,
    shelf_labeled_at = EXCLUDED.shelf_labeled_at,
    barcode = EXCLUDED.barcode,
    reserved_stock = EXCLUDED.reserved_stock,
    vendor_upc = EXCLUDED.vendor_upc,
    counterpoint_item_key = EXCLUDED.counterpoint_item_key,
    track_low_stock = EXCLUDED.track_low_stock,
    web_published = EXCLUDED.web_published,
    web_price_override = EXCLUDED.web_price_override,
    web_gallery_order = EXCLUDED.web_gallery_order,
    counterpoint_prc_2 = EXCLUDED.counterpoint_prc_2,
    counterpoint_prc_3 = EXCLUDED.counterpoint_prc_3,
    nuorder_id = EXCLUDED.nuorder_id,
    on_layaway = EXCLUDED.on_layaway,
    default_location_id = EXCLUDED.default_location_id;

INSERT INTO product_variants (
    product_id,
    sku,
    barcode,
    counterpoint_item_key,
    variation_values,
    variation_label,
    retail_price_override,
    cost_override,
    stock_on_hand,
    reorder_point,
    reserved_stock,
    on_layaway
)
SELECT
    p.id,
    'CP-' || p.catalog_handle,
    NULL,
    p.catalog_handle,
    '{}'::jsonb,
    NULL,
    NULL,
    NULL,
    0,
    0,
    0,
    0
FROM products p
WHERE p.data_source = 'counterpoint'
  AND p.catalog_handle IN ('100', '105', '110', '200')
ON CONFLICT (sku) DO UPDATE SET
    product_id = EXCLUDED.product_id,
    barcode = EXCLUDED.barcode,
    counterpoint_item_key = EXCLUDED.counterpoint_item_key,
    variation_values = EXCLUDED.variation_values,
    variation_label = EXCLUDED.variation_label,
    retail_price_override = EXCLUDED.retail_price_override,
    cost_override = EXCLUDED.cost_override,
    stock_on_hand = EXCLUDED.stock_on_hand,
    reorder_point = EXCLUDED.reorder_point,
    reserved_stock = EXCLUDED.reserved_stock,
    on_layaway = EXCLUDED.on_layaway;
