-- Backfill audit ledgers that earlier production-integrity probes exposed.
-- Safe/idempotent:
-- 1. Counterpoint-linked variants with current stock but no movement history get a
--    baseline inventory adjustment at their original variant creation timestamp.
-- 2. Legacy returned commissionable lines missing return-adjustment events get the
--    same negative commission event now generated by the live return path.

INSERT INTO public.inventory_transactions (
    variant_id,
    tx_type,
    quantity_delta,
    unit_cost,
    reference_table,
    reference_id,
    notes,
    created_at
)
SELECT
    pv.id,
    'adjustment'::public.inventory_tx_type,
    COALESCE(pv.stock_on_hand, 0),
    COALESCE(pv.cost_override, p.base_cost, 0),
    'counterpoint_inventory_baseline',
    NULL,
    'Counterpoint inventory baseline ledger backfill for current stock-on-hand',
    COALESCE(pv.created_at, now())
FROM public.product_variants pv
INNER JOIN public.products p ON p.id = pv.product_id
WHERE NULLIF(TRIM(COALESCE(pv.counterpoint_item_key, '')), '') IS NOT NULL
  AND COALESCE(pv.stock_on_hand, 0) <> 0
  AND COALESCE(p.pos_line_kind, '') = ''
  AND NOT EXISTS (
      SELECT 1
      FROM public.inventory_transactions it
      WHERE it.variant_id = pv.id
  );

INSERT INTO public.commission_events (
    staff_id,
    transaction_id,
    transaction_line_id,
    source_event_id,
    event_type,
    event_at,
    reporting_date,
    commissionable_amount,
    base_rate_used,
    base_commission_amount,
    incentive_amount,
    adjustment_amount,
    total_commission_amount,
    snapshot_json,
    note,
    created_by_staff_id
)
SELECT
    tl.salesperson_id,
    trl.transaction_id,
    trl.transaction_line_id,
    trl.id,
    'return_adjustment',
    COALESCE(trl.created_at, now()),
    (COALESCE(trl.created_at, now()) AT TIME ZONE 'UTC')::date,
    0,
    0,
    0,
    0,
    -ROUND((tl.calculated_commission * trl.quantity_returned / NULLIF(tl.quantity, 0))::numeric, 2),
    -ROUND((tl.calculated_commission * trl.quantity_returned / NULLIF(tl.quantity, 0))::numeric, 2),
    jsonb_build_object(
        'transaction_short_id', COALESCE(t.short_id, 'TXN-' || left(t.id::text, 8)),
        'product_name', p.name,
        'returned_quantity', trl.quantity_returned,
        'sold_quantity', tl.quantity,
        'reason', COALESCE(NULLIF(TRIM(trl.reason), ''), 'return'),
        'source', 'Return adjustment backfill'
    ),
    COALESCE(NULLIF(TRIM(trl.reason), ''), 'return'),
    trl.staff_id
FROM public.transaction_return_lines trl
INNER JOIN public.transaction_lines tl ON tl.id = trl.transaction_line_id
INNER JOIN public.transactions t ON t.id = trl.transaction_id
LEFT JOIN public.products p ON p.id = tl.product_id
WHERE t.status::text <> 'cancelled'
  AND tl.salesperson_id IS NOT NULL
  AND COALESCE(tl.calculated_commission, 0) > 0
  AND COALESCE(tl.quantity, 0) > 0
  AND NOT EXISTS (
      SELECT 1
      FROM public.commission_events ce
      WHERE ce.source_event_id = trl.id
        AND ce.event_type = 'return_adjustment'
  )
  AND ROUND((tl.calculated_commission * trl.quantity_returned / NULLIF(tl.quantity, 0))::numeric, 2) <> 0
ON CONFLICT (source_event_id, event_type)
WHERE source_event_id IS NOT NULL
DO NOTHING;
