use std::fs;
use std::path::Path;
use std::process::Command;

fn main() {
    println!("cargo:rerun-if-changed=../migrations");
    println!("cargo:rerun-if-env-changed=GITHUB_SHA");

    // Inject git SHA so update_check.rs can detect same-version rebuilds.
    // CI sets GITHUB_SHA; local builds fall back to `git rev-parse HEAD`; then "dev".
    let sha = std::env::var("GITHUB_SHA")
        .ok()
        .filter(|s| !s.is_empty())
        .or_else(|| {
            Command::new("git")
                .args(["rev-parse", "HEAD"])
                .output()
                .ok()
                .filter(|o| o.status.success())
                .map(|o| String::from_utf8_lossy(&o.stdout).trim().to_string())
                .filter(|s| !s.is_empty())
        })
        .unwrap_or_else(|| "dev".to_string());

    println!("cargo:rustc-env=RIVERSIDE_GIT_SHA={sha}");

    let migrations_dir = Path::new("../migrations");
    let mut entries = fs::read_dir(migrations_dir)
        .unwrap()
        .map(|res| res.unwrap())
        .filter(|e| {
            let name = e.file_name().into_string().unwrap();
            name.ends_with(".sql") && name.chars().next().unwrap().is_ascii_digit()
        })
        .collect::<Vec<_>>();

    // Sort by filename version number (numerical sort)
    entries.sort_by_key(|e| {
        let name = e.file_name().into_string().unwrap();
        let num_part = name.split('_').next().unwrap().to_string();
        num_part.parse::<i32>().unwrap_or(0)
    });

    let mut code = String::new();
    code.push_str("// This file is autogenerated by build.rs. Do not edit.\n\n");
    code.push_str("#[rustfmt::skip]\n");
    code.push_str("pub const EMBEDDED_MIGRATIONS: &[(&str, &str)] = &[\n");

    for entry in entries {
        let file_name = entry.file_name().into_string().unwrap();
        code.push_str(&format!(
            "    ({:?}, include_str!({:?})),\n",
            file_name,
            format!("../../migrations/{}", file_name)
        ));
    }

    code.push_str("];\n");

    let out_dir = Path::new("src");
    fs::write(out_dir.join("embedded_migrations.rs"), code).unwrap();
}
