use std::fs;
use std::path::Path;

fn main() {
    println!("cargo:rerun-if-changed=../migrations");

    let migrations_dir = Path::new("../migrations");
    let mut entries = fs::read_dir(migrations_dir)
        .unwrap()
        .map(|res| res.unwrap())
        .filter(|e| {
            let name = e.file_name().into_string().unwrap();
            name.ends_with(".sql") && name.chars().next().unwrap().is_ascii_digit()
        })
        .collect::<Vec<_>>();

    // Sort by filename version number (numerical sort)
    entries.sort_by_key(|e| {
        let name = e.file_name().into_string().unwrap();
        let num_part = name.split('_').next().unwrap().to_string();
        num_part.parse::<i32>().unwrap_or(0)
    });

    let mut code = String::new();
    code.push_str("// This file is autogenerated by build.rs. Do not edit.\n\n");
    code.push_str("#[rustfmt::skip]\n");
    code.push_str("pub const EMBEDDED_MIGRATIONS: &[(&str, &str)] = &[\n");

    for entry in entries {
        let file_name = entry.file_name().into_string().unwrap();
        code.push_str(&format!(
            "    ({:?}, include_str!({:?})),\n",
            file_name,
            format!("../../migrations/{}", file_name)
        ));
    }

    code.push_str("];\n");

    let out_dir = Path::new("src");
    fs::write(out_dir.join("embedded_migrations.rs"), code).unwrap();
}
