//! Bundled staff portrait keys; list is generated by `client` script `npm run generate:staff-avatars`.

include!("staff_avatar_allowlist.inc");

#[inline]
pub fn is_allowed_staff_avatar_key(s: &str) -> bool {
    let t = s.trim();
    !t.is_empty() && ALLOWED_STAFF_AVATAR_KEYS.contains(&t)
}
